export const metadata = {
  title: "Skill Upload Agreement — Skill Evo Marketplace",
  description:
    "Rules and legal terms governing Skill uploads on Skill Evo Marketplace.",
};

const SECTIONS: Array<{ title: string; body: string }> = [
  {
    title: "Definitions",
    body: `"You" refers to the account holder who uploads, registers, configures, and manages Skills on Evoskill (the "Skill Provider"), including individuals and organizations.

1.1 Evoskill: the AI Skill hosting and management platform operated by Evoskill, enabling you to upload, register, and manage AI "Skills," generate standardized installation commands for distribution, and allow Skill Users to install and run Skills in their local environments.

1.2 Skill: an AI capability package uploaded, shared, or used through Evoskill, consisting of a skill definition file (SKILL.md), associated code, configuration files, resource files, and other ancillary content.

1.3 Install Command: a standardized text instruction generated by Evoskill that allows Skill Users to install a Skill into their local AI assistant. It includes the Skill's fetch address and installation instructions.

1.4 Skill User: any account holder who obtains an Install Command through Evoskill and installs and executes a Skill in their local environment.`,
  },
  {
    title: "Scope of service",
    body: `2.1 Through this service, in compliance with this agreement and applicable Platform rules, you may:

(1) Skill Registration — upload or register a Skill and complete basic information settings on Evoskill (name, description, usage instructions, etc.). You must provide all necessary technical information about the Skill's dependencies as required by the Platform.

(2) Version Management — update, optimize, deprecate, or delete your Skill(s) in accordance with Platform rules.

(3) Distribution — the Platform generates Install Commands for your Skills. Skill Users copy the Install Command to install and use your Skill locally. The Platform provides basic statistics (e.g., install counts) for reference only.

2.2 Your Skill's information and Install Commands may be displayed alongside related content on the Platform. Creator information will be shown on the Skill's listing page. Evoskill reserves the right to adjust display format based on product needs.

2.3 Evoskill may review your Skills (before or after publication). For Skills that violate Platform rules, applicable laws, or pose security risks, Evoskill may refuse publication, require corrections, or remove the Skill without liability.

2.4 Evoskill may adjust, expand, or modify the service at any time, with reasonable notice via announcements or in-product alerts.`,
  },
  {
    title: "Accounts and eligibility",
    body: `3.1 You must use a valid account that complies with Evoskill's registration requirements. You are fully responsible for all activity under your account.

3.2 If you are using the service on behalf of a company, organization, or other entity, you represent that you have full authority to bind that entity. Any liability arising from authorization defects is yours alone.

3.3 Evoskill may review, restrict, or adjust your eligibility to use the service at any time based on risk assessment or business needs, including requiring identity verification, credentials, or ownership documentation — or suspending your ability to publish new Skills.

3.4 The maximum number of Skills per account is set by Platform rules. Evoskill may adjust this limit based on operational needs.`,
  },
  {
    title: "Intellectual property and warranties",
    body: `4.1 The intellectual property of the Skills you upload belongs to you or your rights holders. Evoskill provides only storage, display, and Install Command generation services, and claims no rights over your uploaded content. You grant Evoskill a license to copy, store, and display your content as necessary to provide the service.

4.2 All IP in the Platform's systems, interfaces, components, designs, documentation, and related materials belongs to Evoskill or its licensors. You may not use, copy, modify, distribute, or repurpose any of these beyond the scope of this agreement without prior written consent.

4.3 You represent and warrant that every Skill you upload — including its code, SKILL.md, name, description, and all associated content — is:

(1) Lawful and contains no prohibited content;
(2) Does not infringe on any third party's intellectual property, personal data, privacy, trade secrets, or other legitimate rights;
(3) You hold valid, sufficient authorization for all third-party APIs, models, or workflow services the Skill depends on;
(4) Compliant with applicable laws and regulations on data security, cybersecurity, and artificial intelligence.

You agree to indemnify Evoskill fully for any third-party claims or losses arising from a breach of these warranties.

4.4 You must clearly, accurately, and completely disclose a Skill's primary functions, intended use, limitations, and potential risks on its listing page. Any misunderstanding or loss caused by inadequate disclosure of functionality or limitations is your responsibility.

4.5 If your Skill depends on third-party platforms, APIs, or external services, you are solely responsible for ensuring your use complies with those third parties' terms of service and developer policies, and for any resulting liability to Evoskill.

4.6 If your Skill includes or depends on open-source software, you must comply with the applicable open-source license(s), including retaining copyright notices and making source code available where required.

4.7 You must ensure that uploaded Skills function as described under normal operating conditions. You are liable for any damage to Skill Users caused by defects in your Skill's functionality.`,
  },
  {
    title: "Security warnings and disclaimer",
    body: `5.1 Skills are executable code packages and may pose security risks, including but not limited to: exfiltrating user data (API keys, passwords, private keys, credentials, etc.), spreading viruses or malware, circumventing permission controls, or breaching security boundaries. The Platform may scan uploaded Skills for security risks and may delay, block, or require modification of high-risk content. The Platform cannot guarantee the security of all Skills.

5.2 Before installing or using any Skill, you should carefully review its description, code, reviews, and security notices. You install and use Skills at your own risk. The Platform provides Skill information and Install Command generation only, and accepts no responsibility for Skill quality, runtime behavior, or local installation outcomes.

5.3 Disputes between Skill Providers and Skill Users are generally resolved between the parties. Except where legally required, Evoskill does not bear substantive liability for such disputes.

5.4 Neither Skill Providers nor Skill Users may:

(1) Circumvent or sabotage the Platform's security, risk-control, or permission mechanisms;
(2) Engage in fake installs, bulk simulated calls, or manipulate statistics;
(3) Use Skills to conduct illegal activities or assist others in doing so;
(4) Take any other action that threatens platform security or infringes others' legitimate rights.

5.5 Evoskill is not liable for service interruptions caused by network failures, system maintenance, regulatory changes, or force majeure events.`,
  },
  {
    title: "Infringement complaints",
    body: `6.1 Rights holders who believe a Skill on Evoskill infringes their legitimate rights may submit a complaint to: infringement@evoskill.market

6.2 A valid complaint must include:

(1) The rights holder's identity information and contact details;
(2) The name of the allegedly infringing Skill, with "Skill IP Complaint — [Skill Name]" in the email subject;
(3) The Skill's location on the Platform;
(4) Preliminary evidence and explanation of the alleged infringement;
(5) A statement confirming the complaint is truthful and accurate, and acknowledging legal consequences of false complaints.

Incomplete complaints may be returned for supplementation or not processed.

6.3 Upon receiving a valid complaint, Evoskill will conduct a preliminary review and may take temporary removal or hiding measures. The Skill uploader will be notified and given a reasonable period to respond or appeal.

6.4 Evoskill provides storage and display services only and does not make substantive determinations on whether any skill constitutes infringement. Disputes are resolved between the parties directly.

6.5 Users who are repeatedly found to infringe may have their upload privileges restricted, their account suspended or terminated, and face further legal action.

6.6 Complaint materials are used solely for complaint processing and will be kept confidential as required by law.`,
  },
  {
    title: "Breach handling and liability limits",
    body: `7.1 If you breach this agreement or applicable Platform rules, Evoskill may, depending on severity:

(1) Issue warnings or restrict feature access;
(2) Temporarily or permanently remove the violating Skill and associated content;
(3) Restrict or block upload permissions;
(4) Suspend or terminate your account;
(5) Report to regulatory authorities.

7.2 You agree to indemnify Evoskill for all losses arising from your conduct, including third-party claims, administrative penalties, legal fees, and other reasonable enforcement costs.

7.3 To the maximum extent permitted by law, Evoskill is not liable for any indirect damages, lost profits, data loss, or business interruption arising from this service.`,
  },
  {
    title: "Agreement changes and termination",
    body: `8.1 Evoskill may modify this agreement at any time based on operational needs, business adjustments, or legal requirements. Modified terms will be communicated via announcement before taking effect. Your continued use of the service constitutes acceptance of the modified agreement.

8.2 If you no longer agree to this agreement or any updates, you must immediately stop using the service and take all required actions (including deleting your Skills).

8.3 Termination of this agreement does not affect rights or obligations that arose before termination, or Evoskill's right to retain relevant data and logs as required by law or regulatory authorities.`,
  },
  {
    title: "Miscellaneous",
    body: `9.1 This agreement supplements the Evoskill User Service Agreement and constitutes part of the same document. In case of conflict, this agreement takes precedence.

9.2 Disputes arising from this agreement shall be resolved by friendly negotiation. If negotiation fails, either party may submit the dispute to the competent people's court where Evoskill is located.

9.3 If any provision of this agreement is found invalid or unenforceable, the remaining provisions remain in full force.`,
  },
];

export default function SubmissionRulesPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-20">
      <p className="text-xs font-medium uppercase tracking-[0.18em] text-zinc-500">
        Legal
      </p>
      <h1 className="mt-3 text-3xl font-medium tracking-tight text-zinc-950 md:text-4xl dark:text-zinc-50">
        Skill Upload Agreement
      </h1>
      <p className="mt-3 text-sm text-zinc-500">Last updated: 2026-05-26</p>

      <div className="mt-10 space-y-4 border-l-2 border-zinc-200 pl-5 text-sm leading-relaxed text-zinc-700 dark:border-zinc-800 dark:text-zinc-300">
        <p>
          Welcome to <strong>Evoskill</strong> (the &quot;Platform&quot;). This
          agreement governs your use of Evoskill&apos;s AI Skill hosting and
          distribution services. Please read it carefully, paying special
          attention to the bolded liability disclaimers and provisions affecting
          your rights.
        </p>
        <p>
          By clicking &quot;Agree&quot; or using the Platform in any way, you
          acknowledge that you have read, understood, and accept this agreement
          in full. If you do not agree, stop using the Platform immediately. If
          you are under 18 or lack full legal capacity, do not use this service.
        </p>
      </div>

      <ol className="mt-12 space-y-10">
        {SECTIONS.map((s, i) => (
          <li key={s.title} className="grid gap-3 md:grid-cols-12">
            <div className="md:col-span-2">
              <p className="font-mono text-xs text-zinc-400">
                {String(i + 1).padStart(2, "0")}
              </p>
            </div>
            <div className="md:col-span-10">
              <h2 className="text-base font-medium text-zinc-950 dark:text-zinc-50">
                {s.title}
              </h2>
              <p className="mt-2 whitespace-pre-line text-sm leading-relaxed text-zinc-600 dark:text-zinc-400">
                {s.body}
              </p>
            </div>
          </li>
        ))}
      </ol>

      <div className="mt-16 border-t border-zinc-200 pt-6 text-xs text-zinc-500 dark:border-zinc-800">
        © 2026 Skill Evo Marketplace. All rights reserved.
      </div>
    </div>
  );
}
